### ISSUE TITLE
Enum naming conventions

### ISSUE THREAD

**Issue by pelikhan** [xinabox/pxt-SW01#6]
Enums are capitalized ( https://makecode.com/extensions/naming-conventions )
https://github.com/xinabox/pxt-SW01/blob/caea76cf8c8b52777600ce5aa26714ebbf4a82b4/sw01.ts#L7

**Comment by gotfredsen** [comment]
All code reviewed to conform with [naming standard](https://makecode.com/extensions/naming-conventions)
