### ISSUE TITLE
Anomoly with pressure reporting

### ISSUE THREAD

**Issue by PragmaticPhil** [xinabox/pxt-SW01#8]
Step 1 = create simple program:
OD01.printNumber(SW01.pressure(Pressure.HectoPascal)
OD01.printNumber(SW01.pressure(Pressure.MilliBar)

Step 2 = flash to microbit.  Connect OD01 and SW01 via IM01. microbit powered from laptop

Step 3 = power up the microbit:  
Correct looking values are displayed for hPa and mBar

Step 4 = reset microbit using the reset button
Program runs again.
This time the mBar value is identical to the hPa value.

I have photos.

**Comment by KalbeAbbas** [comment]
Hi, few notes with this issue:

* mBar and hPa have conversion factor of 1
* Different reporting is due to glitch on start, we can safely ignore this.

**Comment by gotfredsen** [comment]
@kj/@pm, has this been fixed? If so please close the issue.

**Comment by KalbeAbbas** [comment]
@gotfredsen, Yes it is. We actually had conversation about it on slack later. @PragmaticPhil, should I close it?

**Comment by PragmaticPhil** [comment]
Sorry - I miss alerts from GH - I get so many I have to send them straight to Junk.
Closed :)
